let teamLabelsCache = { yearID: 'Year',
  lgID: 'League',
  teamID: 'Team',
  franchID: 'Franchise',
  divID: 'Division',
  Rank: 'Standing',
  G: 'Games Played',
  Ghome: 'Games Played At Home',
  W: 'Wins',
  L: 'Losses',
  DivWin: 'Division Winner',
  WCWin: 'Wildcard Winner',
  LgWin: 'League Champion',
  WSWin: 'World Series Winner',
  R: 'Runs Scored',
  AB: 'At Bats',
  H: 'Hits',
  '2B': 'Doubles',
  '3B': 'Triples',
  HR: 'Home Runs',
  BB: 'Walks',
  SO: 'Strike Outs',
  SB: 'Stolen Bases',
  CS: 'Caught Stealing',
  HBP: 'Hit By Pitch',
  SF: 'Sacrifice Flies',
  RA: 'Opponents Runs Scored',
  ER: 'Earned Runs Allowed',
  ERA: 'Earned Run Average',
  CG: 'Complete Games',
  SHO: 'Shutouts',
  SV: 'Saves',
  IPouts: 'Outs Pitched',
  HA: 'Hits Allowed',
  HRA: 'Homeruns Allowed',
  BBA: 'Walks Allowed',
  SOA: 'Strikeouts By Pitchers',
  E: 'Errors',
  DP: 'Double Plays',
  FP: 'Fielding Percentage',
  name: 'Teams Full Name',
  park: 'Teams Home Ballpark',
  attendance: 'Home Attendance Total',
  BPF: 'Three Year Park Factor For Batters',
  PPF: 'Three Year Park Factor For Pitchers' }

exports.teamLabels = function() {
    return teamLabelsCache;
};